site_name: "Hacking Notes"
site_url: https://hec7orci7o.github.io/hacktricks/
copyright: Copyright &copy; 2026 HÃ©ctor T.
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest

plugins:
- search
- social
- optimize

extra_css:
- stylesheets/extra.css

extra_javascript:
- javascripts/extra.js

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/hec7orci7o
    - icon: fontawesome/brands/linkedin 
      link: https://linkedin.com/in/hec7or

nav:
- Welcome: index.md
- Content:
    - Hacking WordPress: content/hacking-wordpress.md
    - Linux Fundamentals: content/linux-fundamentals.md
    - Network Enumeration with Nmap: content/network-enumeration-with-nmap.md
    - Cracking Passwords with Hashcat: content/cracking-passwords-with-hashcat.md
    - File Inclusion: content/file-inclusion.md
    - File Transfers: content/file-transfers.md
    - SQL Injection Fundamentals: content/sql-injection-fundamentals.md
    - Web Requests: content/web-requests.md
    - Using the Metasploit Framework: content/using-the-metasploit-framework.md
    - JavaScript Deobfuscation: content/javascript-deobfuscation.md
    - Windows Fundamentals: content/windows-fundamentals.md
    - Linux Privilege Escalation: content/linux-privilege-escalation.md
    - Attacking Web Applications with Ffuf: content/attacking-web-applications-with-ffuf.md
    - Login Brute Forcing: content/login-brute-forcing.md
    - SQLMap Essentials: content/sqlmap-essentials.md
    - Windows Privilege Escalation: content/windows-privilege-escalation.md
    - Introduction to Active Directory: content/introduction-to-active-directory.md
    - Getting Started: content/getting-started.md
    - Broken Authentication: content/broken-authentication.md
    - Intro to Network Traffic Analysis: content/intro-to-network-traffic-analysis.md
    - Cross-Site Scripting (XSS): content/cross-site-scripting-xss.md
    - Command Injections: content/command-injections.md
    - Using Web Proxies: content/using-web-proxies.md
    - Footprinting: content/footprinting.md
    - Attacking Common Applications: content/attacking-common-applications.md
    - Shells & Payloads: content/shells-payloads.md
    - Attacking Common Services: content/attacking-common-services.md
    - Web Attacks: content/web-attacks.md
    - File Upload Attacks: content/file-upload-attacks.md
    - Active Directory Enumeration & Attacks: 
      - Active Directory Enumeration & Attacks: content/active-directory-enumeration-attacks/index.md
      - Tools of the Trade: content/active-directory-enumeration-attacks/tools.md
    - Information Gathering - Web Edition: content/information-gathering-web-edition.md
    - Server-side Attacks: content/server-side-attacks.md
    - Password Attacks: content/password-attacks.md
    - Pivoting, Tunneling, and Port Forwarding: content/pivoting-tunneling-port-forwarding.md
    - Introduction to Windows Command Line: content/introduction-to-windows-command-line.md
    - Windows Attacks & Defense: content/windows-attacks-and-defense.md
    - Security Monitoring & SIEM Fundamentals: content/security-monitoring-siem-fundamentals.md
    - Attacking GraphQL: content/attacking-graphql.md
    - Web Fuzzing: content/web-fuzzing.md
    - Pentest in a Nutshell: content/pentest-in-a-nutshell.md

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn